"""gen_rosters.py : the six enemy casts, typed from the owner's roster documents (7 Oct 2026), -> GDScript for roster_data.gd.
Each row: slot, character_id, name, role, sex, species, voice_type, named, persona, behavior, normal, combat, damaged, critical, fighter."""
PITCH = {"male_masked": 0.80, "female": 1.15, "male": 0.90, "female_alien": 1.25, "male_alien": 0.70, "male_augmented": 0.55,
         "male_alien_masked": 0.70, "male_alien_augmented": 0.55, "male_masked_hive": 0.80, "female_hive": 1.15, "male_hive": 0.90,
         "female_alien_hive": 1.25, "female_hive_augmented": 1.05, "neutral_machine_echo": 0.60, "neutral_machine_echo_heavy": 0.50,
         "neutral_machine_echo_command": 0.55}
W = [70.0, 10.0, 6.0, 5.0, 8.0, 1.0]
F = {
 "Phenom": ("The Ascendant Houses", "PH", [
  (1, "phenom_01_aurelian_guard", "Aurelian Guard", "Common House Soldier", "male", "Phenom Humanoid", "male_masked", False, "disciplined, formal, contemptuous of lesser civilizations, obedient to House command", "patrols, station defense, boarding, phase-assisted assaults", "low, filtered, precise", "cold, clipped, efficient", "strained, furious, still controlled", "breathless, defiant, contemptuous", "phenom_fighter"),
  (2, "phenom_02_vyrela", "Vyrela", "Skyblade Pilot", "female", "Phenom Humanoid", "female", True, "proud, competitive, elegant, highly skilled, dismissive of weak opponents", "interceptor combat, dueling, precision pursuit, high-speed phase maneuvers", "cool, confident, refined", "sharp, fast, precise", "furious, teeth clenched, personally offended", "intense, defiant, relentless", "phenom_interceptor"),
  (3, "phenom_03_thalen", "Thalen", "Void Strategist", "male", "Phenom Humanoid", "male", True, "analytical, patient, calculating, condescending, strategically brilliant", "fleet coordination, trap setting, route denial, tactical phase-field planning", "deep, measured, intellectual", "calm, tactical", "angry, colder, more threatening", "grim, calculating, relentless", "phenom_scout"),
  (4, "phenom_04_isara", "Isara", "Echo Seer", "female", "Phenom Humanoid", "female_alien", True, "mysterious, quiet, perceptive, unsettlingly calm, intensely loyal to Ascendant doctrine", "detects hidden ships, phase distortions, anomalies, and enemy movement before ordinary sensors", "soft, resonant, slightly doubled", "calm, prophetic, precise", "angry, layered, unusually intense", "cold, echoing, defiant", "phenom_scout"),
  (5, "phenom_05_ascendant_guard", "Ascendant Guard", "House Elite", "male", "Phenom Humanoid", "male_masked", False, "intimidating, disciplined, elitist, unwavering, absolutely loyal to House leadership", "command protection, elite station defense, phase breach assaults, high-value escort", "deep, filtered, authoritative", "commanding, severe", "furious, uncompromising", "unwavering, hostile", "phenom_heavy"),
  (6, "phenom_06_xerathion", "Xerathion", "House Primarch", "male", "Phenom Ascendant", "male_augmented", True, "calm, superior, strategic, charismatic, convinced that Phenom ascendance is inevitable", "commands Houses, directs major phase offensives, leads high-level invasions and monumental fleet actions", "deep, resonant, slow, authoritative", "calm, overwhelming, absolute", "furious but still regal, personally focused", "defiant, wrathful, commanding", "phenom_heavy")]),
 "Kaijurai": ("Keepers of the Behemoths", "KJ", [
  (1, "kaijurai_01_containment_trooper", "Containment Trooper", "Common Containment Soldier", "male", "Kaijurai Alien", "male_alien_masked", False, "disciplined, obedient, fearless around kaiju, procedural", "", "low, filtered, alien resonance", "clipped, forceful", "strained, furious", "", "kaijurai_dart"),
  (2, "kaijurai_02_zhara", "Zhara Keth", "Beast-Handler / Pilot", "female", "Kaijurai Alien", "female_alien", True, "commanding, instinctive, fearless, fascinated by apex creatures", "guides living weapons, manages restraint fields, pilots handler craft", "controlled, resonant", "sharp, authoritative", "enraged, protective of her beast", "", "kaijurai_dart"),
  (3, "kaijurai_03_drakk", "Drakk Vorn", "Warden", "male", "Heavy Kaijurai Alien", "male_alien", True, "brutal, patient, immovable, duty-bound", "guards containment sectors, suppresses breaches, leads heavy response teams", "deep, gravelly, deliberate", "severe", "roaring, relentless", "", "kaijurai_heavy"),
  (4, "kaijurai_04_syrak", "Syrak Nem", "Containment Scientist / Pilot", "female", "Kaijurai Alien", "female_alien", True, "brilliant, clinical, ambitious, emotionally fascinated by controlled evolution", "studies behemoth biology, containment systems, hybrid growth and weaponization", "precise, cool", "technical, urgent", "furious, obsessive", "", "kaijurai_heavy"),
  (5, "kaijurai_05_cradle_guard", "Cradle Guard", "Elite Containment Guard", "male", "Kaijurai Alien", "male_alien_masked", False, "elite, intimidating, fanatically loyal, unshakable", "", "deep, filtered, commanding", "severe", "uncompromising", "", "kaijurai_gunship"),
  (6, "kaijurai_06_vorrax", "Vorrax Kael", "Supreme Keeper", "male", "High Kaijurai Alien", "male_alien_augmented", True, "strategic, ancient-minded, dominating, patient, views kaiju as civilization-scale instruments", "commands the Behemoth Cradle, decides deployment of living catastrophes, directs major invasions", "deep, resonant, ceremonial", "absolute, commanding", "wrathful, defiant", "", "kaijurai_gunship")]),
 "Cybermorph": ("The Machine Ascendancy", "CY", [
  (1, "cybermorph_01_unit", "UNIT-01", "Standard Frame", "none", "Cybermorph Machine", "neutral_machine_echo", False, "efficient, obedient, literal, threat-focused", "", "flat synthetic echo", "faster, clipped", "glitching, harsher", "", ""),
  (2, "cybermorph_02_vx_raid", "VX-RAID", "Assault Frame", "none", "Cybermorph Machine", "neutral_machine_echo", True, "aggressive optimization, rapid target prioritization, relentless pursuit", "", "sharper cadence, red-energy distortion", "", "", "", ""),
  (3, "cybermorph_03_orion_k", "ORION-K", "Recon Frame", "none", "Cybermorph Machine", "neutral_machine_echo", True, "analytical, silent, surveillance-driven, predictive", "", "quieter, precise, minimal words", "", "", "", ""),
  (4, "cybermorph_04_nex_m7", "NEX-M7", "Transformation Frame", "none", "Cybermorph Machine", "neutral_machine_echo", True, "adaptive, experimental, tactical, continuously reconfiguring", "", "layered modulation, shifting resonance", "", "", "", ""),
  (5, "cybermorph_05_ax9", "AX-9", "Guardian Frame", "none", "Cybermorph Machine", "neutral_machine_echo_heavy", False, "defensive, absolute, command-protective, unyielding", "", "deeper, slower, heavier reverb", "", "", "", ""),
  (6, "cybermorph_06_prime_nexus", "PRIME-NEXUS", "Command Frame", "none", "Cybermorph Machine Intelligence", "neutral_machine_echo_command", True, "strategic collective intelligence, cold, adaptive, views organic civilization as inefficient", "", "multi-layer synthetic chorus, calm and authoritative", "", "", "", "")]),
 "Solrath": ("The Void Dominion", "SR", [
  (1, "solrath_01_void_trooper", "Void Trooper", "Common Solrath Soldier", "male", "Void-Touched Humanoid", "male_masked", False, "obedient, merciless, disciplined, emotionally suppressed", "", "calm, filtered, cold", "clipped, aggressive", "strained, furious", "", ""),
  (2, "solrath_02_velkira", "Velkira Syth", "Void Raider / Pursuit Pilot", "female", "Void-Blooded Humanoid", "female_alien", True, "cruel, fast, confident, predatory, enjoys pursuit", "", "cool, sharp, taunting", "fast, focused", "enraged, humiliated by resistance", "", ""),
  (3, "solrath_03_kharvek", "Kharvek", "Void Hunter", "male", "Solrath Hunter-Caste", "male_alien", True, "patient, lethal, analytical, relentless", "", "low, deliberate", "precise, threatening", "openly furious", "", ""),
  (4, "solrath_04_nyssara", "Nyssara Veil", "Void Assassin / Infiltration Pilot", "female", "Void-Touched Humanoid", "female", True, "silent, elegant, deceptive, merciless", "", "soft, low, unsettling", "calm, precise", "vicious, personally enraged", "", ""),
  (5, "solrath_05_void_enforcer", "Void Enforcer", "Elite Soldier / Command Guard", "male", "Void-Touched Humanoid", "male_masked", False, "fanatically loyal, brutal, proud of rank", "", "deep, filtered, authoritative", "commanding", "uncompromising", "", ""),
  (6, "solrath_06_azrath", "Azrath Vhol", "Void Commander / Rift Lord", "male", "Ascended Solrath", "male_augmented", True, "highly intelligent, controlled, strategic, terrifying, devoted to Dominion expansion", "", "deep, calm, dominant", "cold, overwhelming", "wrathful but controlled", "", "")]),
 "Gadversee": ("The Sporemother Dominion", "GV", [
  (1, "gadversee_01_thrall", "Hive Thrall Trooper", "Common Infected Soldier", "male", "Infected Humanoid", "male_masked_hive", False, "obedient, predatory, nearly stripped of individuality, still tactically competent", "common patrols, boarding attacks, station defense, spore escort, hive perimeter security", "filtered, wet, low, hive-linked", "clipped, hostile, synchronized", "strained, enraged, spores pulsing through speech", "broken, furious, still obeying the hive", ""),
  (2, "gadversee_02_mireya", "Mireya Bloom", "Seed Carrier Pilot", "female", "Infected Human", "female_hive", True, "calm, eerie, devout to the hive, still faintly remembers her former self", "pilots seed-carrier craft, deploys spore pods, infects settlements, monitors conversion progress", "soft, melodic, unsettling", "serene but threatening", "furious, distorted, grief and rage mixed together", "fragmented, desperate, hive-dominant", ""),
  (3, "gadversee_03_grath", "Grath Vorn", "Veteran Heavy", "male", "Infected Humanoid", "male_hive", True, "brutal, patient, extremely durable, tactically experienced, enjoys close-range domination", "escorts hive ships, heavy assault, defensive anchor, suppression of resistance", "deep, rough, controlled", "forceful, threatening", "enraged, guttural, relentless", "harsh, broken, still advancing", ""),
  (4, "gadversee_04_vesh", "Vesha Mycel", "Spore Witch Ace", "female", "Hive-Altered Humanoid", "female_alien_hive", True, "highly intelligent, mystical in presentation, manipulative, patient, treats infection as transcendence", "elite pilot, psychic/spore coordination, anomaly sensing, high-value conversion missions", "calm, layered, whispering undertone", "focused, hypnotic, predatory", "furious, sharp, losing composure", "shrill layered rage, still commanding nearby thralls", ""),
  (5, "gadversee_05_spore_guard", "Elite Spore Guard", "Elite Hive Soldier", "male", "Infected Humanoid", "male_masked_hive", False, "fanatically loyal, intimidating, relentless, higher cognition than common thralls", "protects Sporemother vessels, hive command nodes, seed vaults, and named leaders", "deep, filtered, resonant", "commanding, aggressive", "furious, uncompromising", "guttural, unyielding", ""),
  (6, "gadversee_06_mother", "Mother Sera", "Sporemother Commander", "female", "Ascended Hive Humanoid", "female_hive_augmented", True, "serene, terrifying, maternal toward the hive, merciless toward resistance, strategic and patient", "directs major hive operations, planet infection campaigns, fleet convergence, and mass conversion", "calm, layered, almost comforting", "commanding, absolute", "enraged, possessive, personally offended by resistance", "layered fury, desperate but still authoritative", "")]),
 "Arctides": ("The Frozen Houses", "AR", [
  (1, "arctides_01_ice_guard", "Ice Guard", "Common Soldier", "male", "Arctides Humanoid", "male_masked", False, "disciplined, silent, loyal, stoic, extremely resilient", "patrols frozen stations, escorts convoys, guards planetary approaches and glacier installations", "low, filtered, restrained", "concise, controlled", "strained, angry, determined", "breathless, cold, unyielding", ""),
  (2, "arctides_02_seryn", "Seryn Vail", "Frostblade Pilot", "female", "Arctides Humanoid", "female", True, "precise, elegant, competitive, proud, calm under pressure", "fast interception, escort duty, precision strike missions", "cool, composed, refined", "sharp, efficient", "furious, teeth clenched, still controlled", "intense, defiant", ""),
  (3, "arctides_03_kaldren", "Kaldren", "Glacier Hunter", "male", "Arctides Humanoid", "male", True, "patient, analytical, relentless, distrustful of outsiders, fiercely protective of Arctides territory", "pursuit missions, hostile-environment tracking, enemy interdiction", "deep, quiet, measured", "tactical, clipped", "angry, forceful", "grim, relentless", ""),
  (4, "arctides_04_lysara", "Lysara", "Shadow Scout", "female", "Arctides Humanoid", "female", True, "observant, quiet, fearless, mysterious, exceptionally patient", "stealth reconnaissance, border monitoring, hidden-route navigation, forward scouting", "soft, low, calm", "precise, minimal", "visibly furious, coldly focused", "quiet, intense, unwavering", ""),
  (5, "arctides_05_house_warden", "House Warden", "Elite Guard", "male", "Arctides Humanoid", "male_masked", False, "intimidating, highly disciplined, proud, protective of Arctides leadership and sacred infrastructure", "command ship guard, palace defense, cryo-station security, elite escort", "deep, filtered, authoritative", "commanding, severe", "furious, uncompromising", "unwavering", ""),
  (6, "arctides_06_vorstane", "Vorstane", "House Lord / Faction Commander", "male", "Arctides Humanoid", "male", True, "ancient-minded, strategic, severe, honorable, demanding, protective of the Frozen Houses", "commands fleets, arbitrates between Houses, directs defense of glacier worlds and orbital fortresses", "deep, calm, authoritative", "measured, commanding", "furious, personally invested, relentless", "defiant, rallying, severe", "")]),
}
q = lambda s: '"' + s.replace('"', '\\"') + '"'
out = []
for fac, (title, code, rows) in F.items():
    out.append('\t%s: {"leader": %s, "title": %s, "pilots": [' % (q(fac), q(rows[5][2]), q(title)))
    for (slot, cid, name, role, sex, species, vt, named, persona, beh, vn, vc, vd, vcr, fighter) in rows:
        pid = "%s_%02d" % (fac.lower(), slot)
        out.append('\t\t{"character_id": %s, "id": %s, "slot": %d, "rank": %d, "unit": %s, "name": %s, "type": %s, "role": %s,' % (q(cid), q(pid), slot, slot, q("%s-%02d" % (code, slot)), q(name), q("Level %d %s" % (slot, role)), q(role)))
        out.append('\t\t\t"sex": %s, "species": %s, "persona": %s, "behavior": %s,' % (q(sex), q(species), q(persona), q(beh)))
        out.append('\t\t\t"voice_id": %s, "voice_sex": %s, "voice_persona": %s, "normal_emotion": %s, "combat_emotion": %s, "damaged_emotion": %s, "critical_emotion": %s,' % (q(cid), q(sex), q(vt), q(vn), q(vc), q(vd), q(vcr)))
        out.append('\t\t\t"fighter_primary": %s, "fighter_alternates": [], "spawn_weight": %.1f, "named_unique": %s, "bounty": false,' % (q(fighter), W[slot - 1], "true" if named else "false"))
        out.append('\t\t\t"voice": %.2f, "female": %s, "hurt": "...Still in the fight..."},' % (PITCH[vt], "true" if sex == "female" else "false"))
    out.append('\t]},')
open('enemy_rosters.gd.txt', 'w').write('\n'.join(out) + '\n'); print(len(out), 'lines')
