#!/usr/bin/env python3
"""make_voice_fx — v1.5j: the sounds played around a spoken line (no samples, pure synthesis) into assets/audio/:
fx_static (radio static burst), fx_robot (machine beep chatter), fx_alien (clicks and a warble), fx_hum (electrical hum
bed, loops). Kept apart from make_sfx.py so the older sounds are never regenerated by accident."""
import os, sys, wave
import numpy as np
SR = 22050
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "../../assets/audio")
rng = np.random.default_rng(11)

def save(name, x, gain=0.85):
    x = np.asarray(x, float); x = x / max(1e-9, np.max(np.abs(x))) * gain
    with wave.open(os.path.join(OUT, name + ".wav"), "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR); w.writeframes((x * 32767).astype("<i2").tobytes())
def t(d): return np.arange(int(SR * d)) / SR
def env(n, a=0.01, r=0.08):
    e = np.ones(n); na = max(1, int(SR * a)); nr = max(1, int(SR * r)); e[:na] = np.linspace(0, 1, na); e[-nr:] *= np.linspace(1, 0, nr); return e
def lowpass(x, fc):
    a = np.exp(-2 * np.pi * fc / SR); y = np.zeros_like(x); p = 0.0
    for i, s in enumerate(x): p = (1 - a) * s + a * p; y[i] = p
    return y

# radio static: band-limited noise with crackle, 0.35 s
n = rng.normal(size=int(SR * 0.35)); st = n - lowpass(n, 900); st = lowpass(st, 4200)
crack = (rng.random(st.size) < 0.004) * rng.normal(size=st.size) * 6
save("fx_static", (st + crack) * env(st.size, 0.005, 0.12), 0.7)

# robot chatter: a run of quick square beeps at stepped pitches, 0.5 s
out = []
for k in range(9):
    f = rng.choice([620, 780, 940, 1180, 1400, 880]); d = rng.uniform(0.025, 0.05)
    tt = t(d); b = np.sign(np.sin(2 * np.pi * f * tt)) * 0.6 + np.sin(2 * np.pi * f * 2 * tt) * 0.2
    out.append(b * env(tt.size, 0.002, 0.008)); out.append(np.zeros(int(SR * rng.uniform(0.01, 0.03))))
save("fx_robot", np.concatenate(out), 0.6)

# alien: wet clicks over a falling warble, 0.5 s
tt = t(0.5); war = np.sin(2 * np.pi * (420 - 260 * tt / 0.5 + 40 * np.sin(2 * np.pi * 9 * tt)) * tt) * 0.35
clicks = np.zeros(tt.size)
for k in range(10):
    i = int(rng.uniform(0, tt.size - 400)); L = 300; cl = rng.normal(size=L) * np.exp(-np.arange(L) / 40.0); clicks[i:i + L] += cl
save("fx_alien", (war + lowpass(clicks, 3000) * 1.2) * env(tt.size, 0.01, 0.1), 0.6)

# hum: 1 s seamless 60 Hz hum with harmonics (whole cycles, loops cleanly)
tt = t(1.0); hum = np.sin(2 * np.pi * 60 * tt) + 0.5 * np.sin(2 * np.pi * 120 * tt) + 0.25 * np.sin(2 * np.pi * 180 * tt) + 0.12 * np.sin(2 * np.pi * 300 * tt)
save("fx_hum", hum, 0.5)
print("ok")
