class_name ArtRefs
extends RefCounted
## GENERATED by tools/art/build_art_refs.py: do not edit by hand. Report: docs/ART_MAP.md.
## Concept-art map (v1.4k): which Drive concept image is the visual reference for each station room and planet
## location. The pictures stay in Drive (concept-art); the game only stores the reference until a picture is turned
## into a room strip. null = no art yet (do not invent it: concept sheet first).

const ROOMS := ["main_hub", "shipyard", "dealer", "weapons_dealer", "supplies", "bar", "mission_board", "rest_quarters"]
const SYSTEMS := {
	"aurelion": {
		"lore": "guide",
		"faction": "Elyza",
		"guards": {
			"armor": ["paladin", "dark_knight"],
			"colors": "royal blue and silver (darker variants allowed)",
			"loadouts": ["big gunblade on the back", "pistol gunblade on the hip", "cape, no large weapon", "other weapon"],
			"recycled_characters": false,
			"none_in": ["rest_quarters"],
		},
		"stations": {
			"Aurelion Citadel": {
				"sheet": null,
				"exterior": {"file": "HOMELANCER_StationExterior_Aurelion-CapitalOrbitalCitadel_16x9_20261004_v1.png", "drive": "1d4ifG_T1J4VgmsjJYNGYKjl3qhi30_Zb"},
				"rooms": {
					"main_hub": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_MainHub_Panorama_16x9_20261004_v1.png", "drive": "1Kx8JlCiyRzUYTrxGGS4dF90ZlbOBdt60"},
					"shipyard": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_Shipyard_Panorama_16x9_20261004_v1.png", "drive": "1qhHeOod9YD23n4ZzurhDE20ujeO6cHUv"},
					"dealer": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_Dealer_Panorama_16x9_20261004_v1.png", "drive": "1gWki5sF2P_787-iquKa3JJLZ-Lz12PEd"},
					"weapons_dealer": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_WeaponsDealer_Panorama_16x9_20261004_v1.png", "drive": "1U9QCDcL_kYqdxYAUmr5oewP_Blid4GvH"},
					"supplies": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_Supplies_Panorama_16x9_20261004_v1.png", "drive": "1U-y7Az9i5Tgzpc-jBP3-b9y4yaNlG3WS"},
					"bar": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_Bar_Panorama_16x9_20261004_v1.png", "drive": "1DQ3Zv0Nx8Ocac_QF7f62UC9zNcSRo1Bn"},
					"mission_board": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_MissionBoard_Panorama_16x9_20261004_v1.png", "drive": "1N7XXlT5ZIsgBe9zclYm9mabhxQWf-oxf"},
					"rest_quarters": {"file": "HOMELANCER_Station_Aurelion-CapitalOrbitalCitadel_Room_Panorama_16x9_20261004_v1.png", "drive": "1dTgYIWpA0CxbS6OFPm3yxA-fmc5eiirL"},
				},
			},
			"Diplomatic and Trade Hub": {
				"sheet": null,
				"exterior": {"file": "HOMELANCER_StationExterior_Aurelion-DiplomaticTradeHub_16x9_20261004_v1.png", "drive": "1KXWQrpRqCzQGravyP4AiejR0lgkpgk59"},
				"rooms": {
					"main_hub": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_MainHub_Panorama_16x9_20261004_v1.png", "drive": "1f7WWvb8HA9hZLLHxZ6ojoWgikXJyFdel"},
					"shipyard": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_Shipyard_Panorama_16x9_20261004_v1.png", "drive": "14ep4HEITKLNdegexgz_itAOZk2vWAoUz"},
					"dealer": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_Dealer_Panorama_16x9_20261004_v1.png", "drive": "12vZY_2WoFV0Ih1bd8hjuxCLwzfmdhBBX"},
					"weapons_dealer": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_WeaponsDealer_Panorama_16x9_20261004_v1.png", "drive": "1g9yAUiWetjPZ-vbmrUskFrgkEl5qMRuf"},
					"supplies": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_Supplies_Panorama_16x9_20261004_v1.png", "drive": "12tdIREZzW6QRTLI6GdmDZELmzOf5Nn3t"},
					"bar": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_Bar_Panorama_16x9_20261004_v1.png", "drive": "1uRe6KaE1nvTJ9pdxUznuquSzItfB2vrp"},
					"mission_board": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_MissionBoard_Panorama_16x9_20261004_v1.png", "drive": "1t_Sx-e4pLSn-qpxfnzFLqXlvORBRtQFq"},
					"rest_quarters": {"file": "HOMELANCER_Station_Aurelion-DiplomaticTradeHub_Room_Panorama_16x9_20261004_v1.png", "drive": "1tfau3yGkMvX2TuhXoOaXhBIjBv3aFsqE"},
				},
			},
			"Aurelion Shipyard": {
				"sheet": null,
				"exterior": {"file": "HOMELANCER_StationExterior_Aurelion-Shipyard_16x9_20261004_v1.png", "drive": "1CVR3HNyxi_luC1g1T07BmDKw2KyrHHo6"},
				"rooms": {
					"main_hub": {"file": "HOMELANCER_Station_Aurelion-Shipyard_MainHub_Panorama_16x9_20261004_v1.png", "drive": "1_62xZhJLgL69-8tov_p-xfGd9M4ZeP20"},
					"shipyard": {"file": "HOMELANCER_Station_Aurelion-Shipyard_Shipyard_Panorama_16x9_20261004_v1.png", "drive": "16HIjxgyx73nnVInfBtaYFH7bNOHl8o3T"},
					"dealer": {"file": "HOMELANCER_Station_Aurelion-Shipyard_Dealer_Panorama_16x9_20261004_v1.png", "drive": "1mYc36qir-S68jUWi8hfjZdEz5HVMHwtN"},
					"weapons_dealer": {"file": "HOMELANCER_Station_Aurelion-Shipyard_WeaponsDealer_Panorama_16x9_20261004_v1.png", "drive": "1Z4vTtWjj8XICNbR3RKslNdUtLS0s94pS"},
					"supplies": {"file": "HOMELANCER_Station_Aurelion-Shipyard_Supplies_Panorama_16x9_20261004_v1.png", "drive": "1OJbIShgIzZSjjCiflBBltfjkj_xxgINt"},
					"bar": {"file": "HOMELANCER_Station_Aurelion-Shipyard_Bar_Panorama_16x9_20261004_v1.png", "drive": "1JvXbloHLRZ3Yldv1_BTG_077pepyVf7b"},
					"mission_board": {"file": "HOMELANCER_Station_Aurelion-Shipyard_MissionBoard_Panorama_16x9_20261004_v1.png", "drive": "1ibqV5cqMoUg8ysmwxXVwWLtR9hYS94OC"},
					"rest_quarters": {"file": "HOMELANCER_Station_Aurelion-Shipyard_Room_Panorama_16x9_20261004_v1.png", "drive": "1baSkJTvUWBiyHQo33qJFTX9yWx3V1So8"},
				},
			},
		},
		"planets": {
			"Aurelion Prime": {
				"sheet": {"code": "A01", "file": "HOMELANCER_PlanetConcept_Aurelion-Prime_16x9_20261005_v1.png", "drive": "1-mbfT1FYbjWCbVG0WRVJq1JXVEezlcVH"},
				"locations": [
					{
						"id": "grovecrown",
						"name": "Grovecrown",
						"aerial": {"file": "HOMELANCER_Planet_Aurelion-Prime_Grovecrown_Aerial_Panorama_16x9_20261005_v1.png", "drive": "11SdAc7vHO5J8qbyY0jA1ye87qIuvkEeI", "code": "A02"},
						"first_person": {"file": "HOMELANCER_Planet_Aurelion-Prime_Grovecrown_FirstPerson_Panorama_16x9_20261005_v1.png", "drive": "1sVL20pwYcIo8AnDTsZ9eEMefS_E-KOj6", "code": "A03"},
					},
					{
						"id": "ley_well_sanctum",
						"name": "Ley-Well Sanctum",
						"aerial": {"file": "HOMELANCER_Planet_Aurelion-Prime_LeyWellSanctum_Aerial_Panorama_16x9_20261005_v2.png", "drive": "10ynTOTe-UjBwsh_hXkmRPzc4tAlyf4DM", "code": "A04"},
						"first_person": {"file": "HOMELANCER_Planet_Aurelion-Prime_LeyWellSanctum_FirstPerson_Panorama_16x9_20261005_v1.png", "drive": "1DAM-JVmOoVTNmYgc5eU0NwYcEI7-5Osd", "code": "A05"},
					},
					{
						"id": "silverfall_lakes",
						"name": "Silverfall Lakes",
						"aerial": {"file": "HOMELANCER_Planet_Aurelion-Prime_SilverfallLakes_Aerial_Panorama_16x9_20261005_v1.png", "drive": "1kfXgmyU2-KJ5j75BI2MflaZzTAtCETAk", "code": "A06"},
						"first_person": {"file": "HOMELANCER_Planet_Aurelion-Prime_SilverfallLakes_FirstPerson_Panorama_16x9_20261005_v1.png", "drive": "1dzhb_EB1SqoZt7mMN53WwdmVSVVXZ3Ji", "code": "A07"},
					},
					{
						"id": "canopy_spire_port",
						"name": "Canopy Spire Port",
						"aerial": {"file": "HOMELANCER_Planet_Aurelion-Prime_CanopySpirePort_Aerial_Panorama_16x9_20261005_v1.png", "drive": "1n7o1wRm_fWJl9t9a32P_nvtTmnE_Q1E_", "code": "A08"},
						"first_person": {"file": "HOMELANCER_Planet_Aurelion-Prime_CanopySpirePort_FirstPerson_Panorama_16x9_20261005_v1.png", "drive": "1HNeIzBcI58HdiIXNtAXHZSBSXte8AYjg", "code": "A09"},
					},
				],
				"scenes": [
					{"id": "alisa_temple_throne", "name": "Alisa's temple throne", "code": "AU01", "file": "HOMELANCER_Scene_Aurelion-Prime_AlisaTempleThrone_16x9_20261005_v1.png", "drive": "1fnUMdyK9L-bq2O3oTa8wIPQHVccvU-lv"},
				],
			},
			"Verdance": null,
			"Lumen": null,
			"Thornwild": null,
			"Calyx": null,
		},
	},
	"scavaris": {
		"lore": "thin",
		"faction": "Savagers",
		"guards": null,
		"stations": {"Salvage Hulk": null},
		"planets": {"Scavaris": null, "Husk": null},
	},
	"crystara": {
		"lore": "locked",
		"faction": "Elyza",
		"guards": {
			"armor": ["paladin", "dark_knight"],
			"colors": "royal blue and silver (darker variants allowed)",
			"loadouts": ["big gunblade on the back", "pistol gunblade on the hip", "cape, no large weapon", "other weapon"],
			"recycled_characters": false,
			"none_in": ["rest_quarters"],
		},
		"note": "Lightsaber-crystal harvest (Crystara), deep mining and vaults (Geode), tempering (Prism), cut and ship (Crystal Refinery). Station proper name still open: Opalvein Refinery or Crystal Refinery.",
		"stations": {"Crystal Refinery": null},
		"planets": {"Crystara": null, "Geode": null, "Prism": null},
	},
}
const FACTION_SHEETS := {
	"cybermorph": [
		{"code": "CM01", "name": "Faction concept sheet", "file": "HOMELANCER_Cybermorph_CM01_FactionConceptSheet_MachinesOnly_16x9_20261005_v2.png", "drive": "1m_AXW_TwkmcHhLZXCB6rxu2Ohb6Pzf6e"},
		{"code": "CM02", "name": "Hexdominator", "file": "HOMELANCER_Cybermorph_CM02_Hexdominator_MachinesOnly_16x9_20261005_v2.png", "drive": "13HOa9wOVGpy5j5vuNA72yZ-CkpULCo9s"},
		{"code": "CM03", "name": "Shardstorm", "file": "HOMELANCER_Cybermorph_CM03_Shardstorm_MachinesOnly_16x9_20261005_v2.png", "drive": "1Im6BpvnFXjggxWipKm-fgGPm4CkwAXEG"},
		{"code": "CM04", "name": "Mothership", "file": "HOMELANCER_Cybermorph_CM04_Mothership_MachinesOnly_16x9_20261005_v2.png", "drive": "1T1K8GV6HTISovczrMsfn5dA-ie1B1pcn"},
		{"code": "CM05", "name": "Invasion scene", "file": "HOMELANCER_Cybermorph_CM05_Invasion_MachinesOnly_16x9_20261005_v2.png", "drive": "1TVDfSq6MV2rshLtM97KxXr2r44Ty3O91"},
	],
}

## Write the references into the system data: station["art"], planet["art"] (found by name), sys["art_guards"].
static func apply(systems: Dictionary) -> Dictionary:
	for sid in SYSTEMS:
		if not systems.has(sid): continue
		var sys: Dictionary = systems[sid]
		var a: Dictionary = SYSTEMS[sid]
		sys["art_guards"] = a["guards"]
		sys["art_lore"] = a["lore"]
		for body in [sys["station"], sys["planet"]] + sys.get("more_stations", []) + sys.get("more_planets", []):
			var table: Dictionary = a["stations"] if a["stations"].has(body["name"]) else a["planets"]
			if table.has(body["name"]): body["art"] = table[body["name"]]
	return systems

## The reference for one hub room of a station, or {} when there is no art yet.
static func room(sid: String, station: String, room_id: String) -> Dictionary:
	var s = SYSTEMS.get(sid, {}).get("stations", {}).get(station)
	if s == null: return {}
	var r = s["rooms"].get(room_id)
	return r if r != null else {}

## Everything still without art, as plain lines (the report uses the same list).
static func missing() -> Array:
	var out: Array = []
	for sid in SYSTEMS:
		var a: Dictionary = SYSTEMS[sid]
		for nm in a["stations"]:
			var s = a["stations"][nm]
			if s == null: out.append("%s / %s: concept sheet, exterior and all %d rooms" % [sid, nm, ROOMS.size()])
			else:
				if s["sheet"] == null: out.append("%s / %s: concept sheet" % [sid, nm])
				for r in ROOMS:
					if s["rooms"].get(r) == null: out.append("%s / %s: %s" % [sid, nm, r])
		for nm in a["planets"]:
			if a["planets"][nm] == null: out.append("%s / planet %s: concept sheet and locations" % [sid, nm])
	return out
