class_name RosterData
extends RefCounted
## Job AA (v1.4w): the six-character casts of seven more factions, copied from the owner's roster documents
## ("<FACTION> - Character Roster, Personas, Voice IDs & Image Pairing v1"; Orion is the v2.0 text). Each document
## is a matched pair with its roster picture; names, sex, species, voice type, rank and persona come from the
## DOCUMENT, never from the picture. Slot 01 = common masked soldier, slot 05 = elite masked soldier (both may
## appear many times); slots 02, 03, 04, 06 = named, persistent people. No dialogue lines were invented here.
## Portraits: assets/enemy_pilots/<faction>_0N_clean.jpg / _damaged.jpg. Fighters: "" = that faction has no
## fighter model in the game yet, so its people are known (faces, FACTION page) but do not fly.

const TITLES := {"Covenant": "The Sacred Reach", "Imperium": "The Iron Dominion", "Solarion": "Children of the Sun", "Unity": "The Human Alliance", "Elyza": "The Crystal Frontier", "Orion": "The Pathfinder Nations", "Liberator": "The Free Systems"}

const ROSTERS := {
	"Covenant": {"leader": "Archon Selen", "title": "The Sacred Reach", "pilots": [
		{"character_id": "covenant_01_acolyte", "id": "covenant_01", "slot": 1, "rank": 1, "unit": "CO-01", "name": "Covenant Acolyte", "type": "Level 1 Common Covenant Officer", "role": "Common Covenant Officer",
			"sex": "male", "species": "Covenant Humanoid", "persona": "disciplined, reverent, dutiful, calm, follows sacred protocol", "behavior": "guards stations, escorts pilgrims and officials, obeys hierarchy without hesitation",
			"voice_id": "covenant_01_acolyte", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "filtered, calm, formal", "combat_emotion": "concise, focused", "damaged_emotion": "strained, angry but controlled", "critical_emotion": "breathless, resolute",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 70.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "covenant_02_nerea", "id": "covenant_02", "slot": 2, "rank": 2, "unit": "CO-02", "name": "Nerea Solis", "type": "Level 2 Recon Pilot", "role": "Recon Pilot",
			"sex": "female", "species": "Covenant Humanoid", "persona": "curious, observant, empathetic, faithful, highly intelligent", "behavior": "scouts unfamiliar systems, studies anomalies, prefers understanding before escalation",
			"voice_id": "covenant_02_nerea", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "soft, clear, composed", "combat_emotion": "quick, precise", "damaged_emotion": "angry, hurt, determined", "critical_emotion": "urgent, prayerful but focused",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 10.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "covenant_03_kael", "id": "covenant_03", "slot": 3, "rank": 3, "unit": "CO-03", "name": "Kael Varis", "type": "Level 3 Squadron Leader", "role": "Squadron Leader",
			"sex": "male", "species": "Covenant Humanoid", "persona": "disciplined, tactical, patient, protective, quietly proud", "behavior": "coordinates fighter formations and defends sacred infrastructure with precision",
			"voice_id": "covenant_03_kael", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "low, steady, authoritative", "combat_emotion": "tactical, direct", "damaged_emotion": "forceful, angry, focused", "critical_emotion": "grim, unwavering",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 6.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "covenant_04_lyra", "id": "covenant_04", "slot": 4, "rank": 4, "unit": "CO-04", "name": "Lyra Shan", "type": "Level 4 Celestial Priest / Elite Pilot", "role": "Celestial Priest / Elite Pilot",
			"sex": "female", "species": "Covenant Alien Humanoid", "persona": "serene, mystical, analytical, fearless, deeply connected to Covenant celestial doctrine", "behavior": "combines navigation, ritual knowledge, and elite combat skill; interprets unusual cosmic phenomena for the fleet",
			"voice_id": "covenant_04_lyra", "voice_sex": "female", "voice_persona": "female_alien", "normal_emotion": "calm, ethereal, deliberate", "combat_emotion": "focused, almost meditative", "damaged_emotion": "visibly angry, intense, spiritually resolute", "critical_emotion": "quiet, defiant, unwavering",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 5.0, "named_unique": true, "bounty": false,
			"voice": 1.25, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "covenant_05_hierarch_guard", "id": "covenant_05", "slot": 5, "rank": 5, "unit": "CO-05", "name": "Hierarch Guard", "type": "Level 5 Elite Pilot / Sacred Guard", "role": "Elite Pilot / Sacred Guard",
			"sex": "male", "species": "Covenant Humanoid", "persona": "stern, unwavering, devout, intimidating, protective of high-ranking clergy and command assets", "behavior": "guards temple stations, command ships, relics, high council members, and strategic celestial mechanisms",
			"voice_id": "covenant_05_hierarch_guard", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "deep, filtered, formal", "combat_emotion": "commanding, severe", "damaged_emotion": "angry, uncompromising", "critical_emotion": "resolute, unyielding",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 8.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "covenant_06_selen", "id": "covenant_06", "slot": 6, "rank": 6, "unit": "CO-06", "name": "Archon Selen", "type": "Level 6 High Council Commander", "role": "High Council Commander",
			"sex": "male", "species": "Covenant Humanoid", "persona": "wise, strategic, disciplined, spiritual, politically sophisticated, quietly intimidating", "behavior": "balances doctrine, diplomacy, and military power; will choose force when Covenant worlds or sacred sites are threatened",
			"voice_id": "covenant_06_selen", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "rich, calm, authoritative", "combat_emotion": "measured, commanding", "damaged_emotion": "colder, visibly angry, personally invested", "critical_emotion": "solemn, defiant, rallying",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 1.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
	]},
	"Imperium": {"leader": "Lord Kraeg", "title": "The Iron Dominion", "pilots": [
		{"character_id": "imperium_01_trooper", "id": "imperium_01", "slot": 1, "rank": 1, "unit": "IM-01", "name": "Imperium Trooper", "type": "Level 1 Common Dominion Soldier", "role": "Common Dominion Soldier",
			"sex": "male", "species": "Human", "persona": "obedient, disciplined, intimidating, loyal to command, trained to suppress resistance without hesitation", "behavior": "common patrol and military presence; follows orders quickly; speaks in short formal phrases",
			"voice_id": "imperium_01_trooper", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "low, filtered, controlled", "combat_emotion": "clipped, aggressive, disciplined", "damaged_emotion": "strained, angry, more forceful", "critical_emotion": "breathless but still obeying command",
			"fighter_primary": "imperium_fighter", "fighter_alternates": [], "spawn_weight": 70.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "imperium_02_vexa", "id": "imperium_02", "slot": 2, "rank": 2, "unit": "IM-02", "name": "Vexa Drak", "type": "Level 2 Strike Pilot", "role": "Strike Pilot",
			"sex": "female", "species": "Human", "persona": "cold, ambitious, competitive, ruthless in pursuit, highly confident", "behavior": "prefers decisive first strikes; dislikes hesitation; treats combat skill as proof of worth",
			"voice_id": "imperium_02_vexa", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "cool, sharp, self-assured", "combat_emotion": "fast, precise, aggressive", "damaged_emotion": "furious, teeth clenched, refusing to disengage", "critical_emotion": "intense, hostile, determined",
			"fighter_primary": "imperium_fighter", "fighter_alternates": [], "spawn_weight": 10.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "imperium_03_garrik", "id": "imperium_03", "slot": 3, "rank": 3, "unit": "IM-03", "name": "Garrik Rend", "type": "Level 3 Veteran Pilot", "role": "Veteran Pilot",
			"sex": "male", "species": "Human", "persona": "experienced, severe, tactical, pragmatic, loyal to victory more than glory", "behavior": "calculates risk, protects formation discipline, distrusts reckless subordinates",
			"voice_id": "imperium_03_garrik", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "deep, measured, blunt", "combat_emotion": "tactical, commanding", "damaged_emotion": "angry, forceful, increasingly personal", "critical_emotion": "grim, relentless",
			"fighter_primary": "imperium_fighter", "fighter_alternates": [], "spawn_weight": 6.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "imperium_04_nyx", "id": "imperium_04", "slot": 4, "rank": 4, "unit": "IM-04", "name": "Nyx Dar'Kesh", "type": "Level 4 Assassin / Elite Pilot", "role": "Assassin / Elite Pilot",
			"sex": "female", "species": "Alien", "persona": "ruthless, predatory, highly intelligent, patient, enjoys psychological pressure, kills efficiently rather than theatrically", "behavior": "hunts high-value targets; speaks quietly; rarely raises her voice until seriously wounded",
			"voice_id": "imperium_04_nyx", "voice_sex": "female", "voice_persona": "female_alien", "normal_emotion": "low, controlled, alien-toned, unsettling", "combat_emotion": "quiet, precise, threatening", "damaged_emotion": "openly furious, harsher, teeth clenched", "critical_emotion": "cold rage, relentless pursuit",
			"fighter_primary": "imperium_gunship", "fighter_alternates": ["imperium_fighter"], "spawn_weight": 5.0, "named_unique": true, "bounty": false,
			"voice": 1.25, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "imperium_05_dominion_guard", "id": "imperium_05", "slot": 5, "rank": 5, "unit": "IM-05", "name": "Dominion Guard", "type": "Level 5 Elite Soldier / Command Guard", "role": "Elite Soldier / Command Guard",
			"sex": "male", "species": "Human", "persona": "elite, fanatically disciplined, intimidating, proud of rank, unquestioning protector of senior command", "behavior": "guards capital ships, command decks, fortress stations, and faction leadership; visibly outranks common troopers",
			"voice_id": "imperium_05_dominion_guard", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "deep, filtered, authoritative", "combat_emotion": "commanding, severe", "damaged_emotion": "furious, uncompromising", "critical_emotion": "unwavering",
			"fighter_primary": "imperium_gunship", "fighter_alternates": [], "spawn_weight": 8.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "imperium_06_kraeg", "id": "imperium_06", "slot": 6, "rank": 6, "unit": "IM-06", "name": "Lord Kraeg", "type": "Level 6 Faction Commander", "role": "Faction Commander",
			"sex": "male", "species": "Human / Augmented", "persona": "terrifyingly calm, strategic, authoritarian, calculating, relentless, believes order justifies extreme force", "behavior": "rarely shouts; dominates through presence and certainty; uses advanced extrasensory/psionic perception rather than ordinary sight",
			"voice_id": "imperium_06_kraeg", "voice_sex": "male", "voice_persona": "male_augmented", "normal_emotion": "deep, slow, resonant, controlled", "combat_emotion": "calm but overwhelming", "damaged_emotion": "colder, angrier, more personally focused", "critical_emotion": "low, defiant, relentless",
			"fighter_primary": "imperium_gunship", "fighter_alternates": [], "spawn_weight": 1.0, "named_unique": true, "bounty": false,
			"voice": 0.55, "female": false, "hurt": "...Still in the fight..."},
	]},
	"Solarion": {"leader": "Valen Aurex", "title": "Children of the Sun", "pilots": [
		{"character_id": "solarion_01_trooper", "id": "solarion_01", "slot": 1, "rank": 1, "unit": "SO-01", "name": "Solarion Trooper", "type": "Level 1 Common Solarion Soldier", "role": "Common Solarion Soldier",
			"sex": "male", "species": "Solarion", "persona": "obedient, disciplined, proud, formal, protective of Solarion infrastructure and civilians", "behavior": "follows orders precisely; does not taunt recklessly; treats combat as duty",
			"voice_id": "solarion_01_trooper", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "calm, filtered, formal", "combat_emotion": "firm, efficient, alert", "damaged_emotion": "strained, angry, determined", "critical_emotion": "breathless but still disciplined",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 70.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "solarion_02_lira", "id": "solarion_02", "slot": 2, "rank": 2, "unit": "SO-02", "name": "Lira Suntide", "type": "Level 2 Recon Pilot", "role": "Recon Pilot",
			"sex": "female", "species": "Solarion", "persona": "perceptive, curious, quick-thinking, highly competitive, loyal, confident in her flying", "behavior": "scouts ahead, reports enemy movement, enjoys testing herself against skilled pilots",
			"voice_id": "solarion_02_lira", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "bright, focused, self-assured", "combat_emotion": "quick, precise", "damaged_emotion": "furious, teeth clenched, refusing to disengage", "critical_emotion": "urgent, intense, still controlled",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 10.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "solarion_03_taron", "id": "solarion_03", "slot": 3, "rank": 3, "unit": "SO-03", "name": "Taron Kael", "type": "Level 3 Veteran Pilot", "role": "Veteran Pilot",
			"sex": "male", "species": "Solarion", "persona": "experienced, stoic, tactical, protective, skeptical of inexperienced pilots", "behavior": "prioritizes survival of the squad and mission success over glory",
			"voice_id": "solarion_03_taron", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "low, measured, confident", "combat_emotion": "concise, tactical", "damaged_emotion": "angry, forceful, focused", "critical_emotion": "grim, defiant",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 6.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "solarion_04_seraph", "id": "solarion_04", "slot": 4, "rank": 4, "unit": "SO-04", "name": "Seraph Nova", "type": "Level 4 Ace Pilot", "role": "Ace Pilot",
			"sex": "female", "species": "Solarion", "persona": "fearless, elegant, highly skilled, proud, demanding of herself and others", "behavior": "enters difficult battles willingly; respects worthy opponents; fiercely protects Solarion citizens",
			"voice_id": "solarion_04_seraph", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "composed, proud, precise", "combat_emotion": "sharp, authoritative", "damaged_emotion": "furious, aggressive, teeth clenched", "critical_emotion": "defiant, relentless",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 5.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "solarion_05_guard", "id": "solarion_05", "slot": 5, "rank": 5, "unit": "SO-05", "name": "Solarion Guard", "type": "Level 5 Elite Soldier", "role": "Elite Soldier",
			"sex": "male", "species": "Solarion", "persona": "intimidating, loyal, disciplined, unwavering, trained to protect high-value Solarion assets", "behavior": "guards reactors, command stations, leadership, and strategic solar infrastructure",
			"voice_id": "solarion_05_guard", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "deep, filtered, formal", "combat_emotion": "commanding, forceful", "damaged_emotion": "angry, uncompromising", "critical_emotion": "unwavering, severe",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 8.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "solarion_06_valen", "id": "solarion_06", "slot": 6, "rank": 6, "unit": "SO-06", "name": "Valen Aurex", "type": "Level 6 Solarion High Commander", "role": "Solarion High Commander",
			"sex": "male", "species": "Solarion", "persona": "intensely proud, strategic, charismatic, disciplined, visionary, protective of Solarion sovereignty", "behavior": "speaks as a leader of a powerful civilization; prefers ordered strength over chaos; will personally commit forces when Solarion worlds are threatened",
			"voice_id": "solarion_06_valen", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "rich, authoritative, measured", "combat_emotion": "commanding, powerful", "damaged_emotion": "furious, personally invested, relentless", "critical_emotion": "defiant, rallying, resolute",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 1.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
	]},
	"Unity": {"leader": "Commander Elara Voss", "title": "The Human Alliance", "pilots": [
		{"character_id": "unity_01_trooper", "id": "unity_01", "slot": 1, "rank": 1, "unit": "UN-01", "name": "Alliance Trooper", "type": "Level 1 Common Alliance Soldier", "role": "Common Alliance Soldier",
			"sex": "male", "species": "Human", "persona": "disciplined, dutiful, calm under pressure, protective of civilians, follows command structure", "behavior": "",
			"voice_id": "unity_01_trooper", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "neutral, filtered, professional", "combat_emotion": "concise, alert", "damaged_emotion": "strained, determined", "critical_emotion": "breathless but controlled",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 70.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "unity_02_mira", "id": "unity_02", "slot": 2, "rank": 2, "unit": "UN-02", "name": "Mira Dane", "type": "Level 2 Academy Pilot", "role": "Academy Pilot",
			"sex": "female", "species": "Human", "persona": "talented, optimistic, curious, eager to prove herself, compassionate, occasionally impulsive", "behavior": "academy and patrol missions",
			"voice_id": "unity_02_mira", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "bright, focused, youthful", "combat_emotion": "quick, responsive", "damaged_emotion": "angry, shaken, fighting through fear", "critical_emotion": "urgent, emotional, still determined",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 10.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "unity_03_rowan", "id": "unity_03", "slot": 3, "rank": 3, "unit": "UN-03", "name": "Rowan Hale", "type": "Level 3 Specialist Pilot", "role": "Specialist Pilot",
			"sex": "male", "species": "Human", "persona": "practical, observant, dry humor, dependable, prefers planning over heroics", "behavior": "academy and patrol missions",
			"voice_id": "unity_03_rowan", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "calm, grounded, slightly dry", "combat_emotion": "tactical, clipped", "damaged_emotion": "frustrated, angry, forceful", "critical_emotion": "grim, steady",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 6.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "unity_04_selene", "id": "unity_04", "slot": 4, "rank": 4, "unit": "UN-04", "name": "Selene Ward", "type": "Level 4 Elite Ace Pilot", "role": "Elite Ace Pilot",
			"sex": "female", "species": "Human", "persona": "precise, fearless, competitive, protective of weaker pilots, strong sense of responsibility", "behavior": "elite escort or interception missions",
			"voice_id": "unity_04_selene", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "confident, composed", "combat_emotion": "sharp, decisive", "damaged_emotion": "furious, teeth clenched, highly focused", "critical_emotion": "defiant, intense",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 5.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "unity_05_elite_guard", "id": "unity_05", "slot": 5, "rank": 5, "unit": "UN-05", "name": "Unity Elite Guard", "type": "Level 5 Elite Military Guard", "role": "Elite Military Guard",
			"sex": "male", "species": "Human", "persona": "disciplined, intimidating, loyal, defensive, assigned to important stations, capital ships and senior officials", "behavior": "",
			"voice_id": "unity_05_elite_guard", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "deep, filtered, formal", "combat_emotion": "commanding", "damaged_emotion": "angry, forceful", "critical_emotion": "unwavering",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 8.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "unity_06_elara", "id": "unity_06", "slot": 6, "rank": 6, "unit": "UN-06", "name": "Commander Elara Voss", "type": "Level 6 Alliance Commander", "role": "Alliance Commander",
			"sex": "female", "species": "Human", "persona": "diplomatic, strategic, empathetic, authoritative, willing to take personal risks to protect the Alliance", "behavior": "reserved for high-importance faction story beats",
			"voice_id": "unity_06_elara", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "calm, commanding, reassuring", "combat_emotion": "firm, strategic", "damaged_emotion": "visibly angry, personally invested, relentless", "critical_emotion": "defiant, commanding, rallying",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 1.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
	]},
	"Elyza": {"leader": "Aurelia Voss", "title": "The Crystal Frontier", "pilots": [
		{"character_id": "elyza_01_soldier", "id": "elyza_01", "slot": 1, "rank": 1, "unit": "EL-01", "name": "Elyza Security Trooper", "type": "Level 1 Common Security Soldier", "role": "Common Security Soldier",
			"sex": "male", "species": "Elyzan", "persona": "disciplined, calm, loyal, professional; protects civilian infrastructure and avoids unnecessary aggression", "behavior": "",
			"voice_id": "elyza_01_soldier", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "calm, filtered, professional", "combat_emotion": "firm, alert", "damaged_emotion": "strained, angry, determined", "critical_emotion": "breathless but disciplined",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 70.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "elyza_02_serin", "id": "elyza_02", "slot": 2, "rank": 2, "unit": "EL-02", "name": "Serin Vale", "type": "Level 2 Vanguard Pilot", "role": "Vanguard Pilot",
			"sex": "female", "species": "Elyzan", "persona": "focused, intelligent, competitive, protective; serious in combat, curious outside battle, dislikes reckless pilots", "behavior": "",
			"voice_id": "elyza_02_serin", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "clear, composed, confident", "combat_emotion": "sharp, focused", "damaged_emotion": "angry, teeth clenched, refusing to retreat", "critical_emotion": "intense, urgent",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 10.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "elyza_03_cael", "id": "elyza_03", "slot": 3, "rank": 3, "unit": "EL-03", "name": "Cael Rhyn", "type": "Level 3 Bounty / Pursuit Specialist", "role": "Bounty / Pursuit Specialist",
			"sex": "male", "species": "Elyzan", "persona": "observant, patient, confident, dry humor; tracks raiders, smugglers and wanted pilots", "behavior": "",
			"voice_id": "elyza_03_cael", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "low, controlled, slightly amused", "combat_emotion": "precise", "damaged_emotion": "openly angry, aggressive", "critical_emotion": "grim determination",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 6.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "elyza_04_lyra", "id": "elyza_04", "slot": 4, "rank": 4, "unit": "EL-04", "name": "Lyra Vey", "type": "Level 4 Ace Specialist", "role": "Ace Specialist",
			"sex": "female", "species": "Elyzan", "persona": "analytical, quiet, fearless, precise; studies opponents before committing and expects competence", "behavior": "",
			"voice_id": "elyza_04_lyra", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "soft, cool, precise", "combat_emotion": "clipped, tactical", "damaged_emotion": "visibly furious but controlled", "critical_emotion": "cold, relentless",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 5.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "elyza_05_elite_guard", "id": "elyza_05", "slot": 5, "rank": 5, "unit": "EL-05", "name": "Elyza Elite Guard", "type": "Level 5 Elite Military Guard", "role": "Elite Military Guard",
			"sex": "male", "species": "Elyzan", "persona": "disciplined, intimidating, loyal, defensive; protects capital ships, critical stations and important officials", "behavior": "",
			"voice_id": "elyza_05_elite_guard", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "deep, filtered, formal", "combat_emotion": "commanding", "damaged_emotion": "angry, forceful", "critical_emotion": "determined",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 8.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "elyza_06_aurelia", "id": "elyza_06", "slot": 6, "rank": 6, "unit": "EL-06", "name": "Aurelia Voss", "type": "Level 6 House Captain / Faction Commander", "role": "House Captain / Faction Commander",
			"sex": "female", "species": "Elyzan", "persona": "regal, diplomatic, exceptionally intelligent, courageous, demanding; treats command as responsibility, not privilege", "behavior": "",
			"voice_id": "elyza_06_aurelia", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "elegant, authoritative, calm", "combat_emotion": "powerful, direct", "damaged_emotion": "furious, teeth clenched, personally determined", "critical_emotion": "commanding, defiant",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 1.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
	]},
	"Orion": {"leader": "Admiral Caleb Rynn", "title": "The Pathfinder Nations", "pilots": [
		{"character_id": "orion_01_survey_trooper", "id": "orion_01", "slot": 1, "rank": 1, "unit": "OR-01", "name": "Orion Survey Trooper", "type": "Level 1 Exploration Infantry / Common Soldier", "role": "Exploration Infantry / Common Soldier",
			"sex": "male", "species": "Human", "persona": "disciplined, curious, cautious, protective, trained for hazardous-world security and expedition defense", "behavior": "common patrols, landing-team security, station defense, escort duty, dangerous survey-zone protection",
			"voice_id": "orion_01_survey_trooper", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "calm, filtered, professional", "combat_emotion": "concise, alert", "damaged_emotion": "strained, angry, determined", "critical_emotion": "breathless, urgent, refusing to abandon the expedition",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 70.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "orion_02_ryan", "id": "orion_02", "slot": 2, "rank": 2, "unit": "OR-02", "name": "Ryan Solace", "type": "Level 2 Explorer Pilot", "role": "Explorer Pilot",
			"sex": "male", "species": "Human", "persona": "adventurous, curious, optimistic, adaptable, eager to chart unknown systems", "behavior": "volunteers for first-contact, survey, and dangerous exploration routes; prefers understanding before shooting",
			"voice_id": "orion_02_ryan", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "warm, confident, focused", "combat_emotion": "alert, practical", "damaged_emotion": "furious, teeth clenched, personally determined", "critical_emotion": "urgent, intense, trying to keep the ship alive",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 10.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "orion_03_syra", "id": "orion_03", "slot": 3, "rank": 3, "unit": "OR-03", "name": "Syra N'Tel", "type": "Level 3 Xenologist / Pilot", "role": "Xenologist / Pilot",
			"sex": "female", "species": "Blue-skinned Alien Humanoid", "persona": "intelligent, empathetic, diplomatic, fascinated by unfamiliar cultures, biology, and ecosystems", "behavior": "first contact, xenobiology, language analysis, alien-world survey missions",
			"voice_id": "orion_03_syra", "voice_sex": "female", "voice_persona": "female_alien", "normal_emotion": "calm, articulate, slightly melodic", "combat_emotion": "precise, controlled", "damaged_emotion": "furious, frightened for her crew, still analytical", "critical_emotion": "strained, urgent, focused",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 6.0, "named_unique": true, "bounty": false,
			"voice": 1.25, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "orion_04_korvax", "id": "orion_04", "slot": 4, "rank": 4, "unit": "OR-04", "name": "Korvax", "type": "Level 4 Science Officer", "role": "Science Officer",
			"sex": "male", "species": "Reptilian Alien", "persona": "methodical, skeptical, dry-witted, highly observant, protective of research crews", "behavior": "anomaly research, hazardous-environment missions, science stations, planetary survey analysis",
			"voice_id": "orion_04_korvax", "voice_sex": "male", "voice_persona": "male_alien", "normal_emotion": "deep, measured, slightly raspy", "combat_emotion": "concise, analytical", "damaged_emotion": "angry, forceful, survival-focused", "critical_emotion": "grim, practical, relentless",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 5.0, "named_unique": true, "bounty": false,
			"voice": 0.70, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "orion_05_vanguard", "id": "orion_05", "slot": 5, "rank": 5, "unit": "OR-05", "name": "Orion Vanguard", "type": "Level 5 Elite Exploration Guard", "role": "Elite Exploration Guard",
			"sex": "male", "species": "Human", "persona": "disciplined, experienced, protective, calm, willing to hold dangerous positions so survey crews can escape", "behavior": "protects senior explorers, research stations, command ships, first-contact teams, and high-risk expeditions",
			"voice_id": "orion_05_vanguard", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "deep, filtered, authoritative", "combat_emotion": "commanding, severe", "damaged_emotion": "furious, uncompromising", "critical_emotion": "unwavering",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 8.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "orion_06_caleb", "id": "orion_06", "slot": 6, "rank": 6, "unit": "OR-06", "name": "Admiral Caleb Rynn", "type": "Level 6 Expedition Commander", "role": "Expedition Commander",
			"sex": "male", "species": "Human", "persona": "experienced, patient, strategic, diplomatic, protective of mixed-species crews", "behavior": "leads major exploration fleets, first-contact expeditions, emergency evacuations, and deep-space missions",
			"voice_id": "orion_06_caleb", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "calm, authoritative, reassuring", "combat_emotion": "commanding, tactical", "damaged_emotion": "furious, protective, personally invested", "critical_emotion": "defiant, rallying, determined",
			"fighter_primary": "", "fighter_alternates": [], "spawn_weight": 1.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
	]},
	"Liberator": {"leader": "Marcus Vale", "title": "The Free Systems", "pilots": [
		{"character_id": "liberator_01_trooper", "id": "liberator_01", "slot": 1, "rank": 1, "unit": "LI-01", "name": "Liberator Trooper", "type": "Level 1 Common Freedom Fighter", "role": "Common Freedom Fighter",
			"sex": "male", "species": "Human", "persona": "determined, practical, loyal to the cause, protective of civilians, distrustful of authoritarian factions", "behavior": "common patrols, boarding defense, station security, militia escort",
			"voice_id": "liberator_01_trooper", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "filtered, direct, informal-professional", "combat_emotion": "quick, alert, aggressive", "damaged_emotion": "strained, angry, defiant", "critical_emotion": "breathless but refusing to surrender",
			"fighter_primary": "liberator_fighter", "fighter_alternates": [], "spawn_weight": 70.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "liberator_02_lena", "id": "liberator_02", "slot": 2, "rank": 2, "unit": "LI-02", "name": "Lena Torres", "type": "Level 2 Tactical Officer", "role": "Tactical Officer",
			"sex": "female", "species": "Human", "persona": "bold, organized, sarcastic, resourceful, deeply committed to protecting free settlements", "behavior": "coordinates small strike teams and asymmetric engagements",
			"voice_id": "liberator_02_lena", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "confident, sharp, energetic", "combat_emotion": "fast, decisive", "damaged_emotion": "angry, teeth clenched, highly focused", "critical_emotion": "defiant, urgent",
			"fighter_primary": "liberator_fighter", "fighter_alternates": [], "spawn_weight": 10.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "liberator_03_brok", "id": "liberator_03", "slot": 3, "rank": 3, "unit": "LI-03", "name": "Brok Tal", "type": "Level 3 Chief Engineer", "role": "Chief Engineer",
			"sex": "male", "species": "Reptilian Alien", "persona": "brilliant, patient, stubborn, dry-witted, proud of making broken machines work", "behavior": "repairs ships, modifies civilian hardware for combat, maintains hidden bases",
			"voice_id": "liberator_03_brok", "voice_sex": "male", "voice_persona": "male_alien", "normal_emotion": "deep, rough, thoughtful", "combat_emotion": "practical, clipped", "damaged_emotion": "irritated, forceful, determined", "critical_emotion": "grim, stubborn",
			"fighter_primary": "liberator_fighter", "fighter_alternates": [], "spawn_weight": 6.0, "named_unique": true, "bounty": false,
			"voice": 0.70, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "liberator_04_kai", "id": "liberator_04", "slot": 4, "rank": 4, "unit": "LI-04", "name": "Kai Mori", "type": "Level 4 Recon Pilot", "role": "Recon Pilot",
			"sex": "female", "species": "Human", "persona": "quiet, fearless, perceptive, independent, highly skilled at infiltration and escape", "behavior": "scouts hostile territory, runs covert routes, supports hidden bases and resistance cells",
			"voice_id": "liberator_04_kai", "voice_sex": "female", "voice_persona": "female", "normal_emotion": "calm, low, focused", "combat_emotion": "precise, tactical", "damaged_emotion": "visibly furious, controlled", "critical_emotion": "cold, relentless",
			"fighter_primary": "liberator_heavy", "fighter_alternates": ["liberator_fighter"], "spawn_weight": 5.0, "named_unique": true, "bounty": false,
			"voice": 1.15, "female": true, "hurt": "...Still in the fight..."},
		{"character_id": "liberator_05_vanguard", "id": "liberator_05", "slot": 5, "rank": 5, "unit": "LI-05", "name": "Liberator Vanguard", "type": "Level 5 Elite Guard", "role": "Elite Guard",
			"sex": "male", "species": "Human", "persona": "disciplined, intimidating, loyal, veteran, willing to hold impossible positions so others can escape", "behavior": "protects commanders, hidden bases, evacuation corridors, critical stations, and high-value convoys",
			"voice_id": "liberator_05_vanguard", "voice_sex": "male", "voice_persona": "male_masked", "normal_emotion": "deep, filtered, authoritative", "combat_emotion": "commanding, severe", "damaged_emotion": "angry, uncompromising", "critical_emotion": "unwavering",
			"fighter_primary": "liberator_heavy", "fighter_alternates": [], "spawn_weight": 8.0, "named_unique": false, "bounty": false,
			"voice": 0.80, "female": false, "hurt": "...Still in the fight..."},
		{"character_id": "liberator_06_marcus", "id": "liberator_06", "slot": 6, "rank": 6, "unit": "LI-06", "name": "Marcus Vale", "type": "Level 6 Fleet Commander", "role": "Fleet Commander",
			"sex": "male", "species": "Human", "persona": "resilient, strategic, charismatic, grounded, distrustful of empires, protective of independent worlds", "behavior": "coordinates fleets and resistance networks; prefers mobility and survival over unnecessary conquest",
			"voice_id": "liberator_06_marcus", "voice_sex": "male", "voice_persona": "male", "normal_emotion": "calm, gravelly, reassuring", "combat_emotion": "commanding, practical", "damaged_emotion": "furious, personally invested, relentless", "critical_emotion": "defiant, rallying",
			"fighter_primary": "liberator_heavy", "fighter_alternates": [], "spawn_weight": 1.0, "named_unique": true, "bounty": false,
			"voice": 0.90, "female": false, "hurt": "...Still in the fight..."},
	]},
}

## The core rosters plus these.
static func merged(core: Dictionary) -> Dictionary:
	var out: Dictionary = core.duplicate(true)
	for f in ROSTERS: out[f] = ROSTERS[f]
	return out
